containers:
  mysql-container:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: typeorm-tutorial
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    health_check:
      command: bash -c 'while !</dev/tcp/mysql-container/3306; do sleep 1; done; echo ok'
      interval: 5s
      retries: 15
      start_period: 5s
      timeout: 1m
    ports:
      - local: 3306
        container: 3306
  